#!/usr/bin/env sh
set -eu
echo "Use Conventional Commits format: type(scope?): message"
echo "Valid types: build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test, BREAKING CHANGE"
echo "Example: feat(login): add login form validation feature"
echo ""
pnpm exec lint-commit --edit "$1"
